// Generated by https://quicktype.io

export interface CategoryResponse {
  metadata:         Metadatum[];
  categoryResponse: CategoryResponseClass;
}

export interface CategoryResponseClass {
  category: Category[];
}

export interface Category {
  id:          number;
  name:        string;
  description: string;
}

export interface Metadatum {
  date: string;
  code: string;
  type: string;
}
